# Generated by Django 2.1.7 on 2019-07-22 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sepomex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('d_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('d_asenta', models.CharField(blank=True, max_length=100, null=True)),
                ('d_tipo_asenta', models.CharField(blank=True, max_length=100, null=True)),
                ('D_mnpio', models.CharField(blank=True, max_length=100, null=True)),
                ('d_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('d_ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('d_CP', models.CharField(blank=True, max_length=100, null=True)),
                ('c_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('c_oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('c_CP', models.CharField(blank=True, max_length=100, null=True)),
                ('c_tipo_asenta', models.CharField(blank=True, max_length=100, null=True)),
                ('c_mnpio', models.CharField(blank=True, max_length=100, null=True)),
                ('id_asenta_cpcons', models.CharField(blank=True, max_length=100, null=True)),
                ('d_zona', models.CharField(blank=True, max_length=100, null=True)),
                ('c_cve_ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
